name: dnstwist daily
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dnstwist
        run: |
          python -m pip install --upgrade pip
          pip install dnstwist

      - name: Run get_dnstwist.py
        working-directory: DNSTWIST
        run: |
          python get_dnstwist.py domains_list.txt
          ls -1 *.csv

      - name: Combine CSVs into single file
        run: |
          mkdir -p DNSTWIST/data
          # take header from first file, then append body from all files skipping their headers
          awk 'FNR==1 && NR!=1{next} {print}' DNSTWIST/*_dnstwist_list.csv > DNSTWIST/data/dnstwist_all.csv
          ls -lh DNSTWIST/data/dnstwist_all.csv

      - name: Commit CSV if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add DNSTWIST/data/dnstwist_all.csv
          git diff --cached --quiet || git commit -m "Update combined dnstwist CSV"
          git push
