name: dnstwist daily
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install dnstwist

      - name: Run script and stage CSV
        run: |
          mkdir -p data
          python get_dnstwist.py domains_list.txt
          latest=$(ls -1t *.csv | head -n 1)
          cp "$latest" data/dnstwist_latest.csv

      - name: Commit CSV if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/dnstwist_latest.csv
          git diff --cached --quiet || git commit -m "Update dnstwist CSV"
          git push
